@echo off
echo [1/5] Initializing Git...
git init
echo [2/5] Adding files (respecting .gitignore)...
git add .
echo [3/5] Committing changes...
git commit -m "Initial commit of Coral Reef Detection & Risk Monitoring System"
echo [4/5] Setting up main branch and remote...
git branch -M main
git remote add origin https://github.com/Mayank556/Coral-Reef-Detection-System-using-Risk-Monitoring.git
echo [5/5] Pushing to GitHub...
git push -u origin main
echo Done!
pause
